server:
  port: ${PORT:8080}

security:
  basic:
    enabled: false
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user

zuul:
  routes:
    security:
      path: /uaa/**
      stripPrefix: false
      serviceId: SECURITY-SERVICE
    product:
      path: /product/**
      serviceId: PRODUCT-SERVICE
    customer:
      path: /customer/**
      serviceId: CUSTOMER-SERVICE
    payment:
      path: /payment/**
      serviceId: PAYMENT-SERVICE
  add-proxy-headers: true

---
spring:
  profiles: docker

security:
  oauth2:
    resource:
      userInfoUri: http://security-service:9999/uaa/user