server:
  port: ${PORT:8081}

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:9999/uaa/user

---

spring:
  profiles: docker

security:
  oauth2:
    resource:
      userInfoUri: http://security-service:9999/uaa/user